### ### ### ### ### ### ### ### ### ### 
# This Bash script extracts eQTL-genes from RegulomeDB JSON files generated by getRegulomeResult.sh.
# It operates on all JSON files in the current directory.
# For each JSON file, the script performs the following steps:
# Reads the contents of the JSON file.
# Uses grep to find lines containing the "method": "eQTLs" string and extracts them.
# Utilizes cut to extract specific fields from the matched lines, separated by commas.
# Applies sed to remove unwanted characters such as double quotes, colons, the word "method," and the word "value."
# Further cleans the extracted eQTL-genes using additional sed commands.
# Concatenates the cleaned eQTL-genes into a single line using xargs echo.
# Saves the extracted eQTL-genes to an output text file with the same base name as the original JSON file, but with the extension changed to .txt.
### ### ### ### ### ### ### ### ### ### 

for f in *.json; do cat "$f" | grep -iE '"method":\s*"eQTLs"[^}]*' -o | cut -d ',' -f 1,5 | sed -r 's/"|:|method|value//gi' | sed 's/\s*eqtls,\s*//gi' | tr '\n' ',' | sed 's/,$/\n/gi' | sed 's/,/, /gi' | xargs echo > "${f%.csv}.txt"; done
